### PR TITLE
Image Classification Web Demo

### PR DESCRIPTION
**Pull request by AK391**
Web Demo on Huggingface Spaces using Gradio for Image classification

### CODE REVIEW

**Comment by s9xie** [comment]
Hi @AK391 - Thanks for the PR. We were trying to build one ourselves. 
I just checked and think this is still based on ImageNet-1K? Any chance you can help with a ImageNet-22K demo using our released 22k pre-trained weights? 

I think this would be super fun and I don't think we have it anywhere in HF right now?

**Comment by AK391** [comment]
@s9xie thanks, I just updated it to use the model from https://github.com/leondgarse/keras_cv_attention_models/releases/download/convnext/convnext_xlarge_imagenet21k-ft1k.h5, 

as it is easier to load the pretrained models from here https://github.com/leondgarse/keras_cv_attention_models/tree/main/keras_cv_attention_models/convnext as noted here https://github.com/stanislavfort/adversaries_to_convnext

but if there is a colab to use the models from the main repo would gladly update for that

**Comment by s9xie** [comment]
Sounds good. Will merge this for now and update later when I get a new colab for 22k.

**Comment by s9xie** [comment]
Hi @AK391 - I made a 22k demo using timm
https://colab.research.google.com/drive/1CBYTIZ4tBMsVL5cqu9N_-Q3TBprqsfEO?usp=sharing

Could you help update the web demo to do this 22k-way classification?

**Comment by AK391** [comment]
@s9xie great, thanks, I have updated the space here https://huggingface.co/spaces/akhaliq/convnext/blob/main/app.py

**Pull request merged**
