### PR TITLE
The url was also wrong

### PR DESCRIPTION
**Pull request by harsh2ai**
Updated the url

Remarks,
There is some issue with model at ``` "convnext_xlarge_1k": "https://dl.fbaipublicfiles.com/convnext/convnext_xlarge_1k_224_ema.pth",```  I have updated the url and dict_key of model urls 
earlier the the 1K model of x_large wasn't loading I fixed that path and variable defined above but while executing I got the issue of 403 error

To further check if everything seems to work right or is it the issue of url only I tried downloading the model weights and using them and it gave me the following error ```PytorchStreamReader failed reading zip archive: failed finding central directory```

It seems that there is some issue with torch hub or model still dosen't exist at torch hub

### CODE REVIEW

**Review by Juankik — APPROVED** [review]

**Comment by Juankik** [comment]
Bien echo

**Review by Juankik — COMMENTED** [review]
Al parecer es correcto?

**Comment by harsh2ai** [comment]
@Juankik yes I cross referenced its correct

**Comment by s9xie** [comment]
We do not have 1k XL model. This pull request seems invalid. Closing for now.

**Pull request closed without merging**
